name: Proxy Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # 每 6 小时运行一次
jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: Ensure package.json exists
        run: |
          if [ ! -f package.json ]; then
            echo "Initializing package.json..."
            bun init -y
          fi
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            bun install
          fi
      - name: Ensure proxyip.ts exists
        run: |
          mkdir -p ./helper
          if [ ! -f ./helper/proxyip.ts ]; then
            echo "console.log('No proxy scan script yet.');" >> ./helper/proxyip.ts
          fi
      - name: Start Scan
        run: bun run ./helper/proxyip.ts
      - name: Publish Result
        if: ${{ success() }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Update proxyip [otcip ci]"
          git pull --rebase https://x-access-token:${GH_PAT}@github.com/avotcorg/proxy.git main
          git push https://x-access-token:${GH_PAT}@github.com/avotcorg/proxy.git main
